import { test } from "node:test";
import assert from "node:assert/strict";
import { loadProject } from "../src/model.mjs";
import { projectContracts, projectAdrs } from "../src/registry.mjs";
import { makeProject, BASE_PROJECT } from "./helpers.mjs";

test("contract registry derives owner and consumers from the tree", () => {
  const { root, cleanup } = makeProject(BASE_PROJECT);
  try {
    const out = projectContracts(loadProject(root));
    assert.match(out, /generated by hsdd registry/);
    // auth-token produced by acme.backend.auth (node) and .1 (phase);
    // consumed by acme.web (node) and acme.backend.auth.2 (phase)
    const authRow = out.split("\n").find((l) => l.includes("`auth-token`"));
    assert.match(authRow, /`acme\.backend\.auth`/);
    assert.match(authRow, /acme\.web/);
    assert.match(authRow, /acme\.backend\.auth\.2/);
    // user-model consumed by acme.backend.auth node and phase .1
    const userRow = out.split("\n").find((l) => l.includes("`user-model`"));
    assert.match(userRow, /acme\.backend\.auth/);
  } finally { cleanup(); }
});

test("consumers column never comes from frontmatter (derived only)", () => {
  const { root, cleanup } = makeProject({
    "contracts/orphan.md": `---
id: orphan
version: v1
status: draft
kind: schema
owner: nobody.owns.this
---

# Contract: orphan

## Interface
{}
`,
  });
  try {
    const out = projectContracts(loadProject(root));
    const row = out.split("\n").find((l) => l.includes("`orphan`"));
    assert.match(row, /\|\s*$|\|\s+\|/); // empty consumers cell
    assert.match(row, /`nobody\.owns\.this`/); // owner falls back to frontmatter
  } finally { cleanup(); }
});

test("adr registry projects id, status, affects", () => {
  const { root, cleanup } = makeProject(BASE_PROJECT);
  try {
    const out = projectAdrs(loadProject(root));
    assert.match(out, /generated by hsdd registry/);
    assert.match(out, /`ADR-001`\s*\|\s*accepted\s*\|\s*acme\.backend\.auth, auth-token@v1/);
  } finally { cleanup(); }
});

test("registries are deterministic and null when the dir is empty", () => {
  const { root, cleanup } = makeProject(BASE_PROJECT);
  try {
    const m = loadProject(root);
    assert.equal(projectContracts(m), projectContracts(m));
    const empty = loadProject("/nonexistent-hsdd-root");
    assert.equal(projectContracts(empty), null);
    assert.equal(projectAdrs(empty), null);
  } finally { cleanup(); }
});
