import { test } from "node:test";
import assert from "node:assert/strict";
import { loadProject } from "../src/model.mjs";
import { deriveStatus, rollupNodes, renderStatusMd } from "../src/status.mjs";
import { makeProject, BASE_PROJECT } from "./helpers.mjs";

const VERIFIED_DOC = `# Verification: acme.backend.auth.1

## Test evidence
- unit: cargo test (42 passed)

## Learnings
- none

## Metrics
- agent wall-clock: 2h 40m

## Human sign-off
`;

test("derives the full lifecycle: planned -> in-progress -> built -> verified -> approved", () => {
  const { root, cleanup } = makeProject({
    ...BASE_PROJECT,
    // auth.1: archived change + verification with evidence + sign-off => approved
    "openspec/changes/archive/acme-backend-auth-1/proposal.md": "Phase: acme.backend.auth.1\n",
    "docs/verify/acme.backend.auth.1.verification.md":
      VERIFIED_DOC + "- reviewed by: purbo date: 2026-07-03\n",
    // auth.2: active change only => in-progress
    "openspec/changes/acme-backend-auth-2/proposal.md": "Phase: acme.backend.auth.2\n",
    // users.1: nothing => planned
  });
  try {
    const rows = deriveStatus(loadProject(root));
    const state = (id) => rows.find((r) => r.phaseId === id).state;
    assert.equal(state("acme.backend.auth.1"), "approved");
    assert.equal(state("acme.backend.auth.2"), "in-progress");
    assert.equal(state("acme.backend.users.1"), "planned");
  } finally { cleanup(); }
});

test("built and verified are distinguished by the verification doc", () => {
  const { root, cleanup } = makeProject({
    ...BASE_PROJECT,
    "openspec/changes/archive/acme-backend-auth-1/proposal.md": "Phase: acme.backend.auth.1\n",
    "openspec/changes/archive/acme-backend-auth-2/proposal.md": "Phase: acme.backend.auth.2\n",
    "docs/verify/acme.backend.auth.2.verification.md": VERIFIED_DOC.replace(/auth\.1/, "auth.2"),
  });
  try {
    const rows = deriveStatus(loadProject(root));
    const state = (id) => rows.find((r) => r.phaseId === id).state;
    assert.equal(state("acme.backend.auth.1"), "built");
    assert.equal(state("acme.backend.auth.2"), "verified"); // evidence but no sign-off
  } finally { cleanup(); }
});

test("node rollup: planned until any child starts, done when all approved", () => {
  const { root, cleanup } = makeProject({
    ...BASE_PROJECT,
    "openspec/changes/archive/acme-backend-users-1/proposal.md": "Phase: acme.backend.users.1\n",
    "docs/verify/acme.backend.users.1.verification.md":
      "# V\n\n## Test evidence\n- ok\n\n## Learnings\n- none\n\n## Human sign-off\n- reviewed by: purbo date: 2026-07-03\n",
  });
  try {
    const m = loadProject(root);
    const nodes = rollupNodes(m, deriveStatus(m));
    const state = (id) => nodes.find((n) => n.nodeId === id).state;
    assert.equal(state("acme.backend.users"), "done");
    assert.equal(state("acme.backend.auth"), "planned");
  } finally { cleanup(); }
});

test("filtering by node id and STATUS.md rendering with metrics", () => {
  const { root, cleanup } = makeProject({
    ...BASE_PROJECT,
    "openspec/changes/archive/acme-backend-auth-1/proposal.md": "Phase: acme.backend.auth.1\n",
    "docs/verify/acme.backend.auth.1.verification.md": VERIFIED_DOC,
  });
  try {
    const m = loadProject(root);
    const scoped = deriveStatus(m, "acme.backend.auth");
    assert.equal(scoped.length, 2);
    const md = renderStatusMd(m, deriveStatus(m));
    assert.match(md, /generated by hsdd status/);
    assert.match(md, /acme\.backend\.auth\.1.*verified/);
    assert.match(md, /agent wall-clock: 2h 40m/);
  } finally { cleanup(); }
});
