// Registry projection (spec v0.5 §3.2). Pure: model in, INDEX.md text out.
// The contract table's owner and consumers columns are DERIVED from node and
// phase produces/consumes declarations; contract frontmatter never carries
// consumers (a field lives in exactly one place).

import { parseIdVersion } from "./frontmatter.mjs";
import { allPhases } from "./model.mjs";

export const GENERATED_HEADER = "<!-- generated by hsdd registry - do not edit by hand -->";

const refersTo = (refs, contractId) =>
  refs.some((r) => parseIdVersion(r).id === contractId);

// Node id producing the contract (phase producers roll up to their node);
// falls back to the contract's own frontmatter owner.
export function deriveOwner(model, contract) {
  const node = model.nodes.find((n) => refersTo(n.produces, contract.id));
  if (node) return node.id;
  const phase = allPhases(model).find((p) => refersTo(p.produces, contract.id));
  if (phase) return phase.node;
  return contract.owner || "";
}

// Sorted node and phase ids consuming the contract. A phase whose consumption
// is already declared by its own node is still listed; both are real consumers.
export function deriveConsumers(model, contract) {
  const ids = [
    ...model.nodes.filter((n) => refersTo(n.consumes, contract.id)).map((n) => n.id),
    ...allPhases(model).filter((p) => refersTo(p.consumes, contract.id)).map((p) => p.id),
  ];
  return [...new Set(ids)].sort();
}

function table(title, header, sep, rows) {
  return [GENERATED_HEADER, "", `# ${title}`, "", header, sep, ...rows, ""].join("\n");
}

export function projectContracts(model) {
  if (model.contracts.length === 0) return null;
  const rows = [...model.contracts]
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((c) =>
      `| \`${c.id}\` | ${c.version} | ${c.kind} | ${c.status} | \`${deriveOwner(model, c)}\` | ${deriveConsumers(model, c).join(", ")} |`);
  return table("Contract Registry",
    "| id | version | kind | status | owner | consumers |",
    "|----|---------|------|--------|-------|-----------|", rows);
}

export function projectAdrs(model) {
  if (model.adrs.length === 0) return null;
  const rows = [...model.adrs]
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((a) => `| \`${a.id}\` | ${a.status} | ${a.affects.join(", ")} |`);
  return table("ADR Registry",
    "| id | status | affects |", "|----|--------|---------|", rows);
}
