// Derived project state (spec v0.5 §7). Pure projections; state is never
// declared, only derived from artifacts that already exist:
//   planned      none of the below
//   in-progress  a linked change exists under openspec/changes/
//   built        the linked change is archived
//   verified     verification doc exists with gate evidence
//   approved     sign-off recorded (merged PR reference or reviewer + date)

import { allPhases } from "./model.mjs";

export const GENERATED_HEADER = "<!-- generated by hsdd status - do not edit by hand -->";

export function derivePhaseState(model, phaseId) {
  const changes = model.changes.filter((c) => c.phaseId === phaseId);
  const verification = model.verifications.find((v) => v.phaseId === phaseId);
  if (verification && verification.hasGateEvidence) {
    return verification.signedOff ? "approved" : "verified";
  }
  if (changes.some((c) => c.archived)) return "built";
  if (changes.length > 0) return "in-progress";
  return "planned";
}

export function deriveStatus(model, nodeId = null) {
  return allPhases(model)
    .filter((p) => !nodeId || p.id === nodeId || p.id.startsWith(nodeId + "."))
    .map((p) => ({
      phaseId: p.id,
      node: p.node,
      name: p.name,
      tier: p.review_tier,
      state: derivePhaseState(model, p.id),
    }));
}

// Node rollup: planned until any child starts, done when all approved,
// in-progress otherwise.
export function rollupNodes(model, rows) {
  return model.nodes
    .filter((n) => n.kind === "leaf-parent")
    .map((n) => {
      const children = rows.filter((r) => r.node === n.id);
      let state = "in-progress";
      if (children.length === 0 || children.every((r) => r.state === "planned")) state = "planned";
      else if (children.every((r) => r.state === "approved")) state = "done";
      return { nodeId: n.id, team: n.team, state, phases: children.length };
    });
}

export function renderStatusTable(rows) {
  const header = "phase                                    state         tier";
  const line = "-".repeat(header.length);
  const body = rows.map((r) =>
    `${r.phaseId.padEnd(40)} ${r.state.padEnd(13)} ${r.tier || ""}`);
  return [header, line, ...body].join("\n");
}

export function renderStatusMd(model, rows) {
  const out = [GENERATED_HEADER, "", "# Project Status", ""];
  out.push("| phase | name | state | tier |");
  out.push("|-------|------|-------|------|");
  for (const r of rows) {
    out.push(`| \`${r.phaseId}\` | ${r.name} | ${r.state} | ${r.tier || ""} |`);
  }
  out.push("");
  const nodes = rollupNodes(model, rows);
  if (nodes.length) {
    out.push("## Nodes", "");
    out.push("| node | state | phases |" + (model.conventions.profile === "multi-team" ? " team |" : ""));
    out.push("|------|-------|--------|" + (model.conventions.profile === "multi-team" ? "------|" : ""));
    for (const n of nodes) {
      out.push(`| \`${n.nodeId}\` | ${n.state} | ${n.phases} |` +
        (model.conventions.profile === "multi-team" ? ` ${n.team || ""} |` : ""));
    }
    out.push("");
  }
  const withMetrics = model.verifications.filter((v) => v.metrics);
  if (withMetrics.length) {
    out.push("## Metrics", "");
    for (const v of withMetrics) {
      out.push(`### ${v.phaseId}`, "");
      out.push(v.metrics, "");
    }
  }
  return out.join("\n");
}
